from turtle import Turtle, Screen

rzuf = Turtle()
rzuf.shape("turtle")
rzuf.color("coral")
rzuf.forward(75)
rzuf.left(90)
rzuf.forward(50)
rzuf.left(90)
rzuf.forward(50)
rzuf.right(90)
rzuf.forward(50)
rzuf.left(90)
rzuf.forward(50)
rzuf.left(90)
rzuf.forward(50)
rzuf.right(90)
rzuf.forward(50)
rzuf.left(90)
rzuf.forward(50)
rzuf.left(90)
rzuf.forward(75)

my_screen = Screen()
my_screen.exitonclick()